---
- name: Nastavení task scheduleru pro automatickou aktualizaci Windows
  hosts: "{{ seznam_stanic }}"
  tasks: 
  - name: Založení tasku v task scheduleru
    win_scheduled_task: 
     name: Update_windows
     description: automatický update windows pomocí Ansible
     start_when_available: yes
     actions: 
     - path: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
       arguments: "{{ ukol }}"
     logon_type: service_account
     username: SYSTEM
     triggers: 
     - days_of_month: 22
       type: monthly
       start_boundary: '2019-04-16T11:00:00'
     state: present
     
