---
- name: Nastavení task scheduleru pro automatickou aktualizaci Windows
  hosts: "{{ seznam_stanic }}"
  tasks: 
#  - name: Kopírování PS skriptu pro update do počítače
#    win_copy: 
#     src: "{{ zdroj }}"
#     dest: "{{ cil }}"
#     remote_src: yes
#    vars: 
#     ansible_become: yes
#     ansible_become_method: runas
#     ansible_become_user: "{{ superucet }}"
#     ansible_become_pass: "{{ superheslo }}"
#     ansible_become_flags: logon_type=new_credentials logon_flags=netcredentials_only
  
  - name: Založení tasku v task scheduleru
    win_scheduled_task: 
     name: Update_windows
     description: automatický update windows pomocí Ansible
     start_when_available: yes
     actions: 
     - path: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
       arguments: "{{ ukol }}"
     logon_type: service_account
     username: SYSTEM
     triggers: 
     - days_of_month: 18
       type: monthly
       start_boundary: '2019-04-16T15:00:00'
     state: present
     
