---
- name: Nahrání tasku pro update do task scheduleru
  hosts: "{{ seznam_stanic }}"
  tasks: 
  - name: Vytvoření tasku
    win_scheduled_task: 
     name: Update_windows
     description: automatický update windows pomocí Ansible
     start_when_available: yes
     actions: 
     - path: cmd.exe
       arguments: 
       #unfinished
    
