---
- name: Nastavení task scheduleru pro automatickou aktualizaci Windows
  hosts: "{{ seznam_stanic }}"
  tasks: 
  - name: Kopírování PS skriptu pro update do počítače
    win_copy: 
     src: "{{ zdroj }}"
     dest: "{{ cil }}"
     remote_src: yes
    vars: 
     ansible_become: yes
     ansible_become_method: runas
     ansible_become_user: "{{ superucet }}"
     ansible_become_pass: "{{ superheslo }}"
     ansible_become_flags: logon_type=new_credentials logon_flags=netcredentials_only
  
  - name: Založení tasku v task scheduleru
    win_scheduled_task: 
     name: Update_windows
     description: automatický update windows pomocí Ansible
     start_when_available: yes
     actions: 
     - path: C:\Ansible\ProvisionCallback_update_58.ps1
     logon_type: service_account
     username: SYSTEM
     triggers: 
     - days_of_month: 17
       type: monthly
       start_boundary: '2019-04-16T16:35:00'
     state: present
     
