---
- name: Updaty počítače
  hosts: "{{ seznam_stanic }}"
  tasks: 
   - name: Povolení služby updatu
     win_command: sc config wuauserv start= auto
     ignore_errors: yes
     
   - name: Povolení updatu
     win_command: sc start wuauserv
     ignore_errors: yes
        
   - name: Updatuje počítač
     win_updates: 
       category_names: [Application,Connectors,CriticalUpdates,DefinitionUpdates,DeveloperKits,FeaturePacks,Guidance,SecurityUpdates,ServicePacks,Tools,UpdateRollups,Updates]
       reboot: no
       state: installed
     ignore_errors: yes
       
   - name: Opětovný zákaz updatu
     win_command: sc stop wuauserv
     ignore_errors: yes
  
   - name: Opětovný zákaz updatu
     win_command: sc config wuauserv start= disabled
